### ISSUE TITLE
Customs skills does not appear for skill checks

### ISSUE THREAD

**Issue by NickOfSon** [AngryBeaver/bsa-pf1#1]
When trying to add a skill check for a recipe there is no opportunity to choose a custom check, for example: you can choose Craft instead of Craft (alchemy). The difference between these 2 skills is that basic "Craft" is only based on your ability modifier, while with a custom one, you can upgrade each level and it becomes better over time

**Comment by AngryBeaver** [comment]
uh yeah well hm i am not that deep into pf1 my implementation here is just straight forward:
Object.entries(CONFIG["PF1"].skills)
also roll for skills is just using the default method actor.rollSkill(skillId).

Do you know how to get those custom skills and roll for them ? else i may invest some time myself but as said i do not really know or use that system at all :-).

**Comment by NickOfSon** [comment]
to add new skill isn't that hard same as roll them. Need to open PC sheet > Skills > Craft > click on "+"
![adding skill](https://github.com/AngryBeaver/bsa-pf1/assets/85431268/38ed093a-7f47-46fa-903c-e1fcce2a3503)

**Comment by AngryBeaver** [comment]
so this means each actor can have own skills. 
The problem is recipes are independent of the actor that is executing them the list of skills available does not parse the actors and should not. 
Why not: first of it looks like you create an id "crft1" for your skill alchemy, maybe another player has set crft1 for a complete diffrent skill ? the programaticall command to execute a skill roll is using the id of the skill actor.rollSkill(skillId)
So the recipe would be using diffrent skills for each actor using it. 
second when you create a recipe for a skill and then delete the only actor that ever has that skill the recipe will probably break.

maybe i am wrong so i will have a look into the source but if it is as i expect by viewing your video this request will not get solved.

**Comment by NickOfSon** [comment]
No matter the result, thanks for your time!

**Comment by AngryBeaver** [comment]
v 1.0.2 released you can now define globally known custom skills. 
Those are then available in recipes.
When the name matches in lowercase an id of a skill this skill is rolled else when it matches the name of a skill.

There are various solutions how you can break it just do not !!

e.g. you could define a skill initially name it alchemy ->this will set the id for this uniq skill then rename it into cooking. Now the skill cooking has an id alchemy you see that could end up bad.

Tested in v10 pf1 9.4 plz let me know if this does not work for other versions.

**Comment by Kubixcube** [comment]
Thanks for this update ! Creating a new skill works perfectly in PF1 !
I couldn't figure how to use it with subskill, but It doesn't matter, creating a new skill is okay !

**Comment by NickOfSon** [comment]
Not working for me in v11, custom skills doesn't appear still

**Comment by Kubixcube** [comment]
You have to go in parameter and look for this module option, there is a new field where you can enter the name of the custom skill.
I am in PF1 V11 too.

**Comment by AngryBeaver** [comment]
You need to define global custom skills:
![image](https://github.com/AngryBeaver/bsa-pf1/assets/10677192/bc58e653-3bb9-4230-ac11-b5ca2f095eee)
then you can use recipes with that skill name:
![image](https://github.com/AngryBeaver/bsa-pf1/assets/10677192/996a6360-3ed4-47c6-83d9-d6c7d8038963)

then set up an custom skill on any character matching the names you used in the setting:
![image](https://github.com/AngryBeaver/bsa-pf1/assets/10677192/c77020f7-391b-4e84-ad6b-cbc0832e86c2)

![image](https://github.com/AngryBeaver/bsa-pf1/assets/10677192/f2910c6d-00ed-42d5-a059-064ce2cfcddc)

fixed for subskills in v1.0.3

**Comment by AngryBeaver** [comment]
tested in v11 now too.
